#!/bin/bash
# SPDX-License-Identifier: MIT

PROGRAM="xxd"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

IDS_FILE="data/arm.ids"
TARGET="include/arm_ids.h"

if ! command -v $PROGRAM &> /dev/null
then
    echo "Error: $PROGRAM not found. Cannot generate arm.ids."
    exit 1
fi

cd "$PROJECT_ROOT" || exit 1

echo "Generating $TARGET from $IDS_FILE..."

cat <<EOF > "$TARGET"
/* SPDX-License-Identifier: MIT */

/**
 * Auto-generated database of ARM CPU implementer and part IDs.
 * 
 * This file contains a pre-compiled byte array representing a text database
 * that maps raw ARM vendor and part hex codes to human-readable processor names
 * (e.g., mapping 0x41/0xd0b to "Cortex-A76").
 * 
 * WARNING: Do not edit this file manually. It is generated by scripts/generate_arm_ids.sh
 * to ensure the binary is self-contained without needing external database files at runtime.
 */

EOF

$PROGRAM -i "$IDS_FILE" >> "$TARGET"

echo "Done!"